#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.docker.local"
OVERRIDE_FILE="$ROOT_DIR/docker-compose.local.yml"
PROJECT_NAME="${COMPOSE_PROJECT_NAME:-zcs-local}"

usage() {
  cat <<'USAGE'
Usage:
  scripts/compose-local.sh up       # build and start mysql/qdrant/backend
  scripts/compose-local.sh down     # stop local compose stack
  scripts/compose-local.sh logs     # follow backend logs
  scripts/compose-local.sh ps       # show containers
  scripts/compose-local.sh restart  # rebuild/restart backend

Local ports:
  backend  http://127.0.0.1:1081
  qdrant   http://127.0.0.1:6333
  mysql    127.0.0.1:3307
USAGE
}

read_env_value() {
  local key="$1"
  local file="$ROOT_DIR/.env"
  if [[ ! -f "$file" ]]; then
    return 0
  fi
  awk -F= -v key="$key" '
    $1 == key {
      value = substr($0, length(key) + 2)
      gsub(/^["'\'']|["'\'']$/, "", value)
      print value
      exit
    }
  ' "$file"
}

ensure_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    chmod 600 "$ENV_FILE"
    return
  fi

  local llm_api_key llm_base_url llm_model embedding_model jwt_secret
  llm_api_key="$(read_env_value LLM_API_KEY)"
  llm_base_url="$(read_env_value LLM_BASE_URL)"
  llm_model="$(read_env_value LLM_MODEL_NAME)"
  embedding_model="$(read_env_value LLM_EMBEDDING_MODEL)"
  jwt_secret="$(read_env_value JWT_SECRET)"

  umask 077
  cat > "$ENV_FILE" <<EOF
# Local docker-compose env. Generated by scripts/compose-local.sh.
# This file is ignored by git. Edit it if you need different local settings.

MYSQL_ROOT_PASSWORD=local_root_password
DATABASE_URL="mysql+aiomysql://root:local_root_password@mysql:3306/saas_agent_db"

LLM_API_KEY="${llm_api_key:-CHANGE_ME}"
LLM_BASE_URL="${llm_base_url:-https://api.openai.com/v1}"
LLM_MODEL_NAME="${llm_model:-gpt-4o-mini}"
LLM_EMBEDDING_MODEL="${embedding_model:-text-embedding-3-small}"

QDRANT_URL="http://qdrant:6333"
QDRANT_API_KEY=""
QDRANT_ON_DISK=False
MEMORY_DB_PATH="./memory_db"
QDRANT_DATA_PATH="./qdrant_data"

UPLOAD_DIR="./uploads"
DEBUG_MODE=True
WEB_CONCURRENCY=1

JWT_SECRET="${jwt_secret:-local-dev-secret-change-me}"
JWT_ALGORITHM="HS256"
JWT_EXPIRE_MINUTES=1440

FRONTEND_ORIGINS="http://localhost:3001,http://127.0.0.1:3001,http://localhost:5173,http://127.0.0.1:5173"
PUBLIC_BASE_URL="http://127.0.0.1:1081"
EOF
  chmod 600 "$ENV_FILE"
  echo "Created $ENV_FILE"
}

compose() {
  docker compose \
    --project-name "$PROJECT_NAME" \
    --env-file "$ENV_FILE" \
    -f "$ROOT_DIR/docker-compose.yml" \
    -f "$OVERRIDE_FILE" \
    "$@"
}

ensure_env_file

cmd="${1:-up}"
case "$cmd" in
  up)
    compose up -d --build mysql qdrant backend
    compose ps
    echo
    echo "Backend: http://127.0.0.1:1081"
    echo "Qdrant : http://127.0.0.1:6333/dashboard"
    ;;
  down)
    compose down
    ;;
  logs)
    compose logs -f backend
    ;;
  ps)
    compose ps
    ;;
  restart)
    compose up -d --build backend
    compose logs -f backend
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
